---
- name: Install unattended upgrades package.
  apt: pkg=unattended-upgrades state=installed

- name: Copy unattended-upgrades configuration files in place.
  template: >
    src=../templates/{{ item }}.j2
    dest=/etc/apt/apt.conf.d/{{ item }}
    owner=root group=root mode=0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
