---
# Simple Drupal Development VM Playbook for Ubuntu 12.04
#
# This playbook will install Drupal on an Ubuntu-based LAMP stack, along with
# drush, composer, and other relevant utilities.
#
# @author Jeff Geerling, 2014

- hosts: all

  vars_files:
  - vars/main.yml

  pre_tasks:
  - include: tasks/init.yml

  roles:
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
    - include: tasks/www.yml
    - include: tasks/drupal.yml
