---
# Ansible playbook for a Drupal LAMP server.
#

- hosts: all
  gather_facts: yes
  sudo: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - include: tasks/init.yml

  roles:
    - geerlingguy.git
    - geerlingguy.firewall
    - security
    - geerlingguy.ntp
    - geerlingguy.postfix
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush

  tasks:
